services:
  - type: web
    name: cora-fastapi
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn predict:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000 